-- DB_SECURITY0925

CREATE DATABASE DB_SECURITY0925;
USE DB_SECURITY0925;

-- TBL_MEMBER_AUTHORITY
CREATE TABLE TBL_MEMBER_AUTHORITY (
	M_AUTHORITY_NO INT AUTO_INCREMENT,
    M_AUTHORITY_ROLE_NAME VARCHAR(20) NOT NULL,
    PRIMARY KEY(M_AUTHORITY_NO)
);
SELECT * FROM TBL_MEMBER_AUTHORITY;

INSERT INTO TBL_MEMBER_AUTHORITY(M_AUTHORITY_ROLE_NAME) VALUES('PRE_USER');
INSERT INTO TBL_MEMBER_AUTHORITY(M_AUTHORITY_ROLE_NAME) VALUES('USER');

-- TBL_MEMBER
CREATE TABLE TBL_MEMBER (
	M_NO INT AUTO_INCREMENT,
    M_ID VARCHAR(20) UNIQUE NOT NULL,
    M_PW VARCHAR(100) NOT NULL,
    M_AUTHORITY_NO TINYINT NOT NULL DEFAULT 1,
    M_ISACCOUNTNONEXPIRED TINYINT 	NOT NULL DEFAULT 1,		-- 만료되지 않음 계정
    M_ISACCOUNTNONLOCKED TINYINT	NOT NULL DEFAULT 1,		-- 계정이 잠기지 않음
    M_ISCREDENTIALSNONEXPIRED TINYINT NOT NULL DEFAULT 1,	-- 만료되지 않은 자격 증명
    M_ISENABLED TINYINT	NOT NULL DEFAULT 1,					-- 활성화됨
    M_REG_DATE DATETIME DEFAULT NOW(),
    M_MOD_DATE DATETIME DEFAULT NOW(),
    PRIMARY KEY(M_NO)
);
SELECT * FROM TBL_MEMBER;


-- TBL_ADMIN_AUTHORITY
CREATE TABLE TBL_ADMIN_AUTHORITY (
	A_AUTHORITY_NO INT AUTO_INCREMENT,
    A_AUTHORITY_ROLE_NAME VARCHAR(20) NOT NULL,
    PRIMARY KEY(A_AUTHORITY_NO)
);
SELECT * FROM TBL_ADMIN_AUTHORITY;

INSERT INTO TBL_ADMIN_AUTHORITY(A_AUTHORITY_ROLE_NAME) VALUES('PRE_ADMIN');
INSERT INTO TBL_ADMIN_AUTHORITY(A_AUTHORITY_ROLE_NAME) VALUES('ADMIN');

-- TBL_ADMIN
CREATE TABLE TBL_ADMIN (
	A_NO INT AUTO_INCREMENT,
    A_ID VARCHAR(20) UNIQUE NOT NULL,
    A_PW VARCHAR(100) NOT NULL,
    A_AUTHORITY_NO TINYINT NOT NULL DEFAULT 1,
    A_ISACCOUNTNONEXPIRED TINYINT 	NOT NULL DEFAULT 1,		-- 만료되지 않음 계정
    A_ISACCOUNTNONLOCKED TINYINT	NOT NULL DEFAULT 1,		-- 계정이 잠기지 않음
	A_ISCREDENTIALSNONEXPIRED TINYINT NOT NULL DEFAULT 1,	-- 만료되지 않은 자격 증명
    A_ISENABLED TINYINT	NOT NULL DEFAULT 1,					-- 활성화됨
    A_REG_DATE DATETIME DEFAULT NOW(),
    A_MOD_DATE DATETIME DEFAULT NOW(),
    PRIMARY KEY(A_NO)
);
SELECT * FROM TBL_ADMIN;